FROM apache/airflow
USER root

RUN apt-get update \ 
    && apt-get install -y default-jdk

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64
RUN export JAVA_HOME

USER airflow
RUN pip install pyspark \
    && pip install apache-airflow-providers-microsoft-mssql\
    && pip install apache-airflow-providers-apache-spark
