FROM apache/airflow:2.8.4
USER root

RUN apt-get update \
    && apt-get install -y build-essential gcc python3-dev\
    && apt-get install -y default-jdk 

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64
RUN export JAVA_HOME

USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    pyspark==3.5.0 \ 
    confluent_kafka
