FROM python:3.11-slim-buster

# Cài đặt các tiện ích cơ bản như 'tail' và 'sleep'
RUN apt-get update \
    && apt-get install -y coreutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN python3 -m venv /opt/vm \
    && /opt/vm/bin/pip install --no-cache-dir requests pandas confluent-kafka==2.11.0

ENV PATH="/opt/vm/bin:$PATH"
